{% set name = "black" %}
{% set version = "18.5b1" %}
{% set sha256 = "c956857a831e508e75f0dc754b86982bad98d95c96aae39c20749209b3958ad7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - black = black:main

requirements:
  build:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - click
    - attrs >=17.4.0
    - appdirs

test:
  commands:
    - black --help

about:
  home: https://github.com/ambv/black
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'The Uncompromising Code Formatter'

  description: |
    Black is the uncompromising Python code formatter. By using it, you agree
    to cease control over minutiae of hand-formatting. In return, Black gives
    you speed, determinism, and freedom from pycodestyle nagging about
    formatting. You will save time and mental energy for more important matters.
  doc_url: https://github.com/ambv/black
  dev_url: https://github.com/ambv/black

extra:
  recipe-maintainers:
    - carlodri
    - ambv
    - mariusvniekerk
    - xhochy
