{% set name = "black" %}
{% set version = "21.12b0" %}
{% set sha256 = "77b80f693a569e2e527958459634f18df9b0ba2625ba4e0c2d5da5be42e6f2b3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - black = black:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - click >=6.5
    - attrs >=18.1.0
    - appdirs
    - toml >=0.9.4

test:
  commands:
    - black --help

about:
  home: https://github.com/python/black
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'The Uncompromising Code Formatter'

  description: |
    Black is the uncompromising Python code formatter. By using it, you agree
    to cease control over minutiae of hand-formatting. In return, Black gives
    you speed, determinism, and freedom from pycodestyle nagging about
    formatting. You will save time and mental energy for more important matters.
  doc_url: https://github.com/python/black
  dev_url: https://github.com/python/black

extra:
  recipe-maintainers:
    - carlodri
    - ambv
    - mariusvniekerk
    - xhochy
