{% set name = "black" %}
{% set version = "0.22.6" %}
{% set sha256 = "6c6d39e28aed379aec40da1c65434c77d75e65bb59a1e1c283de545fb4e7c6c9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - black = black:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - click >=8.0.0
    - platformdirs >=2
    - tomli >=1.1.0     #[<=py310]
    - typed-ast >=1.4.2 #[<py38]
    - pathspec >=0.9.0
    - typing_extensions >=3.10.0.0 #[<py310]
    - mypy_extensions >=0.4.3

test:
  commands:
    - black --help

about:
  home: https://github.com/psf/black
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'The Uncompromising Code Formatter'

  description: |
    Black is the uncompromising Python code formatter. By using it, you agree
    to cease control over minutiae of hand-formatting. In return, Black gives
    you speed, determinism, and freedom from pycodestyle nagging about
    formatting. You will save time and mental energy for more important matters.
  doc_url: https://github.com/psf/black
  dev_url: https://github.com/psf/black

extra:
  recipe-maintainers:
    - carlodri
    - ambv
    - mariusvniekerk
    - xhochy
