{% set name = "black" %}
{% set version = "23.3.0" %}
{% set sha256 = "1c7b8d606e728a41ea1ccbd7264677e494e87cf630e399262ced92d4a8dac940" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - patches/001-remove-fancy-pypi-readme.patch

build:
  number: 0
  skip: True # [py<36]
  script: "{{ PYTHON }} -m pip install --no-deps -vv ."
  entry_points:
    - black = black:patched_main
    - blackd = blackd:patched_main

requirements:
  build:
    - patch                # [unix]
    - m2-patch             # [win]

  host:
    - python
    - pip
    - hatchling
    - hatch-vcs
    - wheel
  run:
    - python
    - click >=8.0.0
    - mypy_extensions >=0.4.3
    - packaging >=22.0
    - pathspec >=0.9.0
    - platformdirs >=2
    - tomli >=1.1.0 # [py<311]
    - typed-ast >=1.4.2 # [py<38]
    - typing_extensions >=3.10.0.0 # [py<310]
  run_constrained:
    - aiohttp >=3.7.4 # for blackd
    - colorama >=0.4.3 # for colorama extra
    - uvloop >=0.15.2 # for uvloop extra
    # - ipython >=7.8.0 # for jupyter extra
    # - tokenize-rt >=3.2.0 for jupyter extra (not in conda defaults currently)
test:
  requires:
    - python
    - pip
  commands:
    - black --help
    - pip check

about:
  home: https://github.com/psf/black
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'The Uncompromising Code Formatter'

  description: |
    Black is the uncompromising Python code formatter. By using it, you agree
    to cease control over minutiae of hand-formatting. In return, Black gives
    you speed, determinism, and freedom from pycodestyle nagging about
    formatting. You will save time and mental energy for more important matters.
  doc_url: https://black.readthedocs.io/en/stable/
  dev_url: https://github.com/psf/black

extra:
  recipe-maintainers:
    - carlodri
    - ambv
    - mariusvniekerk
    - xhochy
