{% set name = "black" %}
{% set version = "22.6.0" %}
{% set sha256 = "6c6d39e28aed379aec40da1c65434c77d75e65bb59a1e1c283de545fb4e7c6c9" %}

package:
  name: {{ name|lower }}-recipe
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

outputs:
  - name: {{ name }}
    build:
      skip: True # [py<36]
      script: "{{ PYTHON }} -m pip install --ignore-installed --no-deps -vv ."
      entry_points:
        - black = black:patched_main

    requirements:
      host:
        - python
        - pip
        - setuptools >=45.0
        - setuptools_scm[toml] >=6.3.1
        - wheel
      run:
        - python
        - click >=8.0.0
        - platformdirs >=2
        - tomli >=1.1.0 # [py<311]
        - typed-ast >=1.4.2 # [py<38]
        - pathspec >=0.9.0
        - typing_extensions >=3.10.0.0 # [py<310]
        - mypy_extensions >=0.4.3
      run_constrained:
        - colorama >=0.4.3
        - uvloop >=0.15.2

    test:
      commands:
        - pip check
        - black --help

  - name: {{ name }}d
    build:
      entry_points:
        - blackd = blackd:patched_main

    requirements:
      run:
        - {{ pin_subpackage('black', max_pin='x.x.x') }}
        - aiohttp >=3.7.4

    test:
      commands:
        - black --help
        - blackd --help

about:
  home: https://github.com/psf/black
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'The Uncompromising Code Formatter'

  description: |
    Black is the uncompromising Python code formatter. By using it, you agree
    to cease control over minutiae of hand-formatting. In return, Black gives
    you speed, determinism, and freedom from pycodestyle nagging about
    formatting. You will save time and mental energy for more important matters.
  doc_url: https://black.readthedocs.io/en/stable/
  dev_url: https://github.com/psf/black

extra:
  recipe-maintainers:
    - carlodri
    - ambv
    - mariusvniekerk
    - xhochy
