travis:
  secure:
    BINSTAR_TOKEN: PFLOdtvvT2ParKOq+BV7rWV5+DvGKyTXfu1KpvhDosWKdzhErHqua4pTCqDPzp/aTIP+dizEXlYzl7AlLwrwk8jkGnPAq/WwQVkkfyfzhOiv8RoCuB926OGh82pCecW1Hmq8yu+LY50CwY229CBFifCgflrdf9X/eDpZOOshfcZ37KFD/3UIz5dL8Q14wcBv0OZ9JbE0SasB9quEXU9+AQh+HJxlIjoE8kzkUgaUD7DTa0KNv2Sy25TtCvw5HHzyT3PfVtT+cIYV1iX5uPorCw12XiwWF2cEZBndwKp7eQXLJ/DILLYGWT+Htlpz3CNA9DcOakpO2178fw6GDJkQ+/uGPhkOz2erl5/DOY5Tuc1xxA9VvnGJMMIk0LLu26KMTt/l8KCBgZ561ea+kRUenQRTvzUU0S1kPud+Z3L3mILGQhNiyBpyE6hRRVeI45B9MA97shq/qyq1Zj4pkE3u82pXUqg7pUPEzYNRl5QAyQ0najwXLdsVfibwXzrsgAWEmMR6LPU+gwQ8Fu6lVP03DE36D0XjGRv4K2Qu/1mM6AG46okD/a9LL4474spTtEq7MuYLuNmfOCfCxlRV5Jbh9X06ScLnTYN0kaAxOti6Bs2SLXjIxYatmZHWsRR+MARGtoFobhN+SQMm6rWyNYGjh9Wp2s9P6Fewi1clLFDkf+M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
